Check if goimports installation succeeds

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -122,6 +122,12 @@ jobs:
           name: Check Go formatting
           command: |
             go install golang.org/x/tools/cmd/goimports@v0.1.1
+            if [ $? -eq 0 ]
+            then
+            else
+              echo "goimports installation failed" >&2
+              exit 1
+            fi
             goimports -d -local "github.com/G-Research/armada" .
             exit $(goimports -l -local "github.com/G-Research/armada" . | wc -l)
 
