Feat(job summary): Implement Job Summaries for Lint workflow

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -26,14 +26,29 @@ jobs:
 
       - name: Check TypeScript formatting
         run: |
-          yarn install --frozen-lockfile && yarn run fmt || exit 1
+          yarn install --frozen-lockfile && yarn run fmt || true
           exit $(git status -s -uno | wc -l)
         working-directory: ./internal/lookout/ui
+        continue-on-error: true  
+
+      - name: Generating TypeScript lint results as summary
+        working-directory: ./internal/lookout/ui
+        if: ${{ always() }}
+        run: |
+           yarn run lint > lint_results.txt || true
+           lint_results=$(cat lint_results.txt)
+           echo -e "## 🪧 Typescript Lint Results\n" >> $GITHUB_STEP_SUMMARY
+           echo -e "* ### ✅ Checked out the repository\n" >> $GITHUB_STEP_SUMMARY
+           echo -e "* ### ✅ Set up tslint and dependencies\n" >> $GITHUB_STEP_SUMMARY
+           if [ ! -z "$lint_results" ]; then
+              echo -e "* ### ⌛ Typescript lint check Passed✅  | Failed❌ | Warning⚠️ \n" >> $GITHUB_STEP_SUMMARY
+              echo -e "${lint_results}" >> $GITHUB_STEP_SUMMARY
+           fi   
+        continue-on-error: true
 
   go-lint:
     name: Lint Go
     runs-on: ubuntu-22.04
-
     steps:
       - name: Checkout
         uses: actions/checkout@v3.3.0
@@ -51,3 +66,21 @@ jobs:
           version: v1.52.2
           only-new-issues: true
           args: --timeout=10m --issues-exit-code=1 --sort-results ./...
+
+      - name: Generating Golang lint results as summary
+        if: ${{ always() }}
+        run: |
+          golangci-lint run > lint_results.txt || true
+          lint_results=$(cat lint_results.txt)
+          echo -e "## 🪧 Golang Lint Results\n" >> $GITHUB_STEP_SUMMARY
+          echo -e "* ### ✅ Checked out the repository\n" >> $GITHUB_STEP_SUMMARY
+          echo -e "* ### ✅ Set up golint and cached dependencies\n" >> $GITHUB_STEP_SUMMARY
+          if [ -z "$lint_results" ]; then
+            echo -e "* ✅ Go lint check passed\n" >> $GITHUB_STEP_SUMMARY
+            echo -e "⚠️  No linting issues found.\n" >> $GITHUB_STEP_SUMMARY
+          else
+              echo -e "* ### ❌ Go lint check failed\n" >> $GITHUB_STEP_SUMMARY
+              echo -e "${lint_results}" >> $GITHUB_STEP_SUMMARY
+          fi
+        continue-on-error: true
+
