revert - remove conditions in jobs for testing Signed-off-by: Ljubo Nikolic <ljubonikolic@gmail.com>
Signed-off-by: Ljubo Nikolić <ljubonikolic@gmail.com>

diff --git a/.github/workflows/release-rc.yml b/.github/workflows/release-rc.yml
--- a/.github/workflows/release-rc.yml
+++ b/.github/workflows/release-rc.yml
@@ -6,16 +6,13 @@ on:
     workflows: [CI]
     branches:
       - master
-      - oss-586-resolve-deprecation-and-warnings
-  push:
-    branches: [oss-586-resolve-deprecation-and-warnings]
 
 permissions:
   contents: write
 
 jobs:
   validate:
-    # if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'armadaproject'
+    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'armadaproject'
     name: "Validate revision"
     runs-on: ubuntu-22.04
 
@@ -28,18 +25,18 @@ jobs:
       # The given ref should belong to the master branch.
       # If it's master, it shouldn't be more than 2 commits away (in case another push happened in the meantime).
       # Anything else is invalid.
-      # - name: Validate ref
-      #   run: |
-      #     ref='${{ github.event.workflow_run.head_branch }}'
-      #     sha='${{ github.event.workflow_run.head_sha }}'
+      - name: Validate ref
+        run: |
+          ref='${{ github.event.workflow_run.head_branch }}'
+          sha='${{ github.event.workflow_run.head_sha }}'
 
-      #     [ "$ref" == "master" ] &&
-      #     [ $(git branch --contains=$sha master | wc -l) -eq 1 ] &&
-      #     [ $(git rev-list --count $sha..master) -le 2 ]
-      #     if [ $? -ne 0 ]; then
-      #       echo "::error ::Invalid ref $ref $sha: must be a merge to master branch and not more than 2 commits away"
-      #       exit 1
-      #     fi
+          [ "$ref" == "master" ] &&
+          [ $(git branch --contains=$sha master | wc -l) -eq 1 ] &&
+          [ $(git rev-list --count $sha..master) -le 2 ]
+          if [ $? -ne 0 ]; then
+            echo "::error ::Invalid ref $ref $sha: must be a merge to master branch and not more than 2 commits away"
+            exit 1
+          fi
   release:
     name: Release
     needs: validate
